USE DesafiosSQL;

DROP TABLE [TABELA DE VENDEDORES];

CREATE TABLE [TABELA DE VENDEDORES]
(
[MATRICULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NOT NULL,
[CIDADE] VARCHAR(100),
[PERCENTUAL COMISSÃO] FLOAT NOT NULL,
[DATA INICIO] DATE NOT NULL,
[TEM_DEPENDENTE] INT NOT NULL
CONSTRAINT [PK_TABELA_DE VENDEDORES] PRIMARY KEY CLUSTERED
)

INSERT INTO [TABELA DE VENDEDORES]
VALUES
(
'00239','Alberto de Sá Verneck','São Paulo',0.08,'2020-06-05',1
)


SELECT * FROM [TABELA DE VENDEDORES];
